//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachingToolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeachingToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Section.
        /// </summary>
        public static string add_section {
            get {
                return ResourceManager.GetString("add_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        public static string add_student {
            get {
                return ResourceManager.GetString("add_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes.
        /// </summary>
        public static string apply_changes {
            get {
                return ResourceManager.GetString("apply_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string attendance {
            get {
                return ResourceManager.GetString("attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Location.
        /// </summary>
        public static string data_location {
            get {
                return ResourceManager.GetString("data_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Section.
        /// </summary>
        public static string delete_section {
            get {
                return ResourceManager.GetString("delete_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        public static string drop {
            get {
                return ResourceManager.GetString("drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        public static string enroll {
            get {
                return ResourceManager.GetString("enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string general_settings {
            get {
                return ResourceManager.GetString("general_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string group_generator {
            get {
                return ResourceManager.GetString("group_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group size:.
        /// </summary>
        public static string group_size {
            get {
                return ResourceManager.GetString("group_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section.
        /// </summary>
        public static string in_section {
            get {
                return ResourceManager.GetString("in_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in this section.
        /// </summary>
        public static string not_in_section {
            get {
                return ResourceManager.GetString("not_in_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of groups:.
        /// </summary>
        public static string number_of_groups {
            get {
                return ResourceManager.GetString("number_of_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomizer.
        /// </summary>
        public static string pick_random {
            get {
                return ResourceManager.GetString("pick_random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate.
        /// </summary>
        public static string regenerate {
            get {
                return ResourceManager.GetString("regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What days class is taking place, e.g. MWF or TuTh.
        /// </summary>
        public static string section_days_watermark {
            get {
                return ResourceManager.GetString("section_days_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of class, e.g. GER 201.
        /// </summary>
        public static string section_name_watermark {
            get {
                return ResourceManager.GetString("section_name_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time does the class start, e.g. 9:20am.
        /// </summary>
        public static string section_time_watermark {
            get {
                return ResourceManager.GetString("section_time_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        public static string sections {
            get {
                return ResourceManager.GetString("sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string students {
            get {
                return ResourceManager.GetString("students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students in {0}.
        /// </summary>
        public static string students_in_section_title {
            get {
                return ResourceManager.GetString("students_in_section_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string timer {
            get {
                return ResourceManager.GetString("timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher&apos;s Toolbox.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
